package:
  name: q2_predict_dysbiosis
  version: 2023.9.11

source:
  path: ../

# make noarch, architecture-independent
build:
    noarch: generic

# Add bioconda channel for biom
extra:
  channels:
    - conda-forge
    - bioconda

requirements:

  build:
    - python=3.6
    - setuptools

  run:
    - python=3.6
    # QIIME 2 things for the setup
    - qiime2 >=2019.1
    - q2-types
    # Other modules used in the actual code
    - biom-format
    - pandas >=1.0.0
    - numpy
    - scipy


about:
  home: https://github.com/Kizielins/q2-predict-dysbiosis
  license: BSD-3-Clause
  license_family: BSD
